
[font]
size = 10.0

[font.bold]
family = "RecMonoCasual Nerd Font"
style = "Bold"

[font.bold_italic]
family = "RecMonoCasual Nerd Font"
style = "Bold Italic"

[font.italic]
family = "RecMonoCasual Nerd Font"
style = "Italic"

[font.normal]
family = "RecMonoCasual Nerd Font"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[window]
opacity = 0.80
blur = true
resize_increments = true # resizes window in descrete steps
dynamic_padding = true # spread padding evenly
option_as_alt = "Both" # only for macOS
decorations = "Buttonless" # hide title bar and buttons (macOS)

[general]
import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]
