import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[font]
size = 10.0

[font.bold]
family = "RecMonoCasual Nerd Font"
style = "Bold"

[font.bold_italic]
family = "RecMonoCasual Nerd Font"
style = "Bold Italic"

[font.italic]
family = "RecMonoCasual Nerd Font"
style = "Italic"

[font.normal]
family = "RecMonoCasual Nerd Font"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

[scrolling]
history = 10000
multiplier = 3

[shell]
program = "/bin/zsh"

[window]
opacity = 0.80
blur = true
